production:
  secret_key_base: "21c288c27cbbe74ab393b7391f760dcfdc716adbf0754a6b153661c2304f73afb9573ecc9b9ad9bffe0bc3040ebb9bef1ebbf59d92d77a29575ba1fa773df141"
 
development:
  stripe_publishable_key: pk_test_YC94Pic1v7jCyzBhi0PX8rLw00cNFJAq3s
  stripe_secret_key: sk_test_C9vU5k64PrDngzzCvGH9CQCa00ZyEvGxwN

production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key'] 